### ISSUE TITLE
checkcode.do 问题

### ISSUE THREAD

**Issue by quicksandznzn** [hxca/58CrackVerification#1]
非常感谢大神的分享 轨道模拟准确率非常高
有一个问题请教一下 
https://callback.58.com/antibot/verifycode?serialId=7dd4e545075c50464036262e240a2583_560760fa54b7474c919886ba6976f6e1&code=22&sign=3b3489663f981b99e36fb9f675720539&namespace=usdt_infodetail_car&url=https%3A%2F%2Finfodetail1.58.com%3A443%2Fbj%2Fershouche%2F41967107313315x.shtml%3Fsesrank_id%3Dbusitime-bs%26TID%3D5e3659c7-6fa3-46f1-ba3c-98b8e9b8c113%26dispcid%3D1%26dispcname%3Dbj%26typos%3Dpromationinfo_l27%26infotype%3Dj_2%26oCate%3D29%26entinfo%3D41967107313315_j%26psid%3D188159396208863314673459126%26ABTEST257%3DWBERSHOUCHE_257
这是我的URL 我通过抓包工具可以发现请求checkcode.do成功后的URL 但是通过代码只会返回{"code":0,"msg":"www.58.com"}

**Comment by hxca** [comment]
返回这个已经验证成功了，这时候更换cookie就行了

**Comment by quicksandznzn** [comment]
> 返回这个已经验证成功了，这时候更换cookie就行了

非常感谢 cookie会失效嘛

**Comment by hxca** [comment]
> > 返回这个已经验证成功了，这时候更换cookie就行了
> 
> 非常感谢 cookie会失效嘛 还请赐教cookie如何获取 - - ~
1. 长期爬取58同城还是会不定时弹出滑动验证的，所以需要自动更新cookie。
2. 
自动更新cookie：
```python
# 通过验证后，随意访问一个 58 同城地址获取更新后的cookie
r = requests.get(url)

# requests session 更新 cookie
session = requests.Session()
session.cookies.update(r.cookies)
```

爬虫发送的请求：
```python
r = session.get(url)
```
